<!-- test version 0.1 -->
<!DOCTYPE html>
<html>
<head>
  <title>Artwork</title>
  <meta charset=utf-8>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <link rel=stylesheet id=pagestyle href=page.css>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossorigin="anonymous"></script>
  <script src="project1.js"></script>
</head>
<body>
    <header class="jumbotron">
      <div class="text-center">
        <h1>Welcome to xxx</h1>
       </div>
    </header>



<!-- end of header.inc -->
